### ISSUE TITLE
Visiting Jed's website results in 404 error

### ISSUE THREAD

**Issue by yduman** [messageformat/Jed#54]
Hi,

when I try to visit the Homepage of Jed, I get a 404. Anyone noticing the same issue?

Sincerely,
yduman

**Comment by alex-stripe** [comment]
We switched it to the messageformat organization for compliance with the js foundation. The github stuff 301s the repo but it doesn't 301 github pages  

If anyone has ideas on how to 301 the page without overriding the repo 301s, I'd love that info.

**Comment by alex-stripe** [comment]
It's here now though: http://messageformat.github.io/Jed/

**Comment by yduman** [comment]
Strangely, a couple of hourse before, the "new" link had a 404 too. But now it's working so nvm 👍 . Thanks!

**Comment by ramonvg** [comment]
It's broken on `README.md`:

> For more info, please visit the docs site at http://messageformat.github.com/Jed.

You should change to the one @alex-stripe wrote.

> For more info, please visit the docs site at https://messageformat.github.io/Jed/

**Comment by Artoria2e5** [comment]
You should also change the Repo URL displayed near the top of https://github.com/messageformat/Jed/.

**Comment by fredrikekelund** [comment]
Bumping this as a quick reminder - the repo URLon GitHub still reads http://slexaxton.github.com/Jed. The README URL on npm is also stuck at the wrong one - might be worth a new patch release. Thanks!
